accounts/passwords/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns  = [
        url(r'^password/change/$', 
                auth_views.PasswordChangeView.as_view(), 
                name='password_change'),
        url(r'^password/change/done/$',
                auth_views.PasswordChangeDoneView.as_view(), 
                name='password_change_done'),
        url(r'^password/reset/$', 
                auth_views.PasswordResetView.as_view(), 
                name='password_reset'),
        url(r'^password/reset/done/$', 
                auth_views.PasswordResetDoneView.as_view(), 
                name='password_reset_done'),
        url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
                auth_views.PasswordResetConfirmView.as_view(), 
                name='password_reset_confirm'),
        url(r'^password/reset/complete/$', 
                auth_views.PasswordResetCompleteView.as_view(), 
                name='password_reset_complete'),
]

accounts/urls.py
from django.conf.urls import url
from booksapp.views import UserProductHistoryView
from .views import (
        AccountHomeView, 
        UserDetailUpdateView,
        )

urlpatterns = [
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'history/books/$', UserProductHistoryView.as_view(), name='user-book-history'),
    url(r'^$', AccountHomeView.as_view(), name='home'),    
]

pustakalaywebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from .views import home_page, contact_page, update_pincode
from accounts.views import LoginView, RegisterView
from django.contrib.auth import views as auth_views
from carts.views import cart_detail_api_view
from django.views.generic import RedirectView
from accounts.views import send_otp_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^update-pincode/$', update_pincode, name='update-pincode'),
    url(r'^sms/', include("sms.urls", namespace='sms')),
    url(r'^orders/', include("orders.urls", namespace='orders')),
    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/', include("addresses.urls", namespace='addresses')),
    url(r'^settings/$', RedirectView.as_view(url='/account')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include("accounts.urls", namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^register/(?P<phonenumber>\d+)/$', RegisterView.as_view(), name='register_page'),
    url(r'^sendotp/$', send_otp_view, name='send-otp'),
    url(r'^contact/$', contact_page, name='contact'),
    url('books/', include('booksapp.urls', namespace='books')),
    url('search/', include('search.urls', namespace='search')),
    url('cart/', include('carts.urls', namespace='carts')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/urls.py
from django.conf.urls import url
from .views import resend_otp, check_balance


urlpatterns = [
    url(r'^check-balance/$', check_balance, name='check-balance'),
    url(r'^resend-otp/$', resend_otp, name='resend-otp'),
    ]

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager
)
from sms.utils import send_transactional_sms

class UserManager(BaseUserManager):
    def create_user(self, phone, full_name=None, password=None, is_active=True, is_staff=False, is_admin=False):
        if not phone:
            raise ValueError("Users must have a phone number")
        if not password:
            raise ValueError("Users must have a password")
        user_obj = self.model(
            phone = phone,
            full_name=full_name
        )
        user_obj.set_password(password) # change user password
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.active = is_active
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, phone,full_name=None, password=None):
        user = self.create_user(
                phone,
                full_name=full_name,
                password=password,
                is_staff=True
        )
        return user

    def create_superuser(self, phone, full_name=None, password=None):
        user = self.create_user(
                phone,
                full_name=full_name,
                password=password,
                is_staff=True,
                is_admin=True
        )
        return user


class User(AbstractBaseUser):
    phone       = models.CharField(max_length=10, unique=True)
    email       = models.EmailField(max_length=255, unique=True, blank=True, null=True)
    full_name   = models.CharField(max_length=255, blank=True, null=True)
    is_active   = models.BooleanField(default=True) # can login 
    staff       = models.BooleanField(default=False) # staff user non superuser
    admin       = models.BooleanField(default=False) # superuser 
    timestamp   = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'phone' 
    # USERNAME_FIELD and password are required by default
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.phone
    
    def get_full_name(self):
        if self.full_name:
            return self.full_name
        return self.phone

    def get_short_name(self):
        if self.full_name:
            return self.full_name
        return self.phone

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

def post_save_user_create_reciever(sender, instance, created, *args, **kwargs):
    if created:
        send_transactional_sms({instance.phone}, "Welcome to Pustakalay.")
#         send message to user.

post_save.connect(post_save_user_create_reciever, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import authenticate, login
from .signals import user_logged_in
from django.contrib.auth.password_validation import validate_password
from sms.utils import verify_otp
import re

User = get_user_model()

class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('phone',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserDetailChangeForm(forms.ModelForm):
    full_name = forms.CharField(label='Name', required=False, widget=forms.TextInput(attrs={"class": 'form-control'}))
    email  = forms.EmailField(widget=forms.EmailInput(attrs={"class": 'form-control'}))
    class Meta:
        model = User
        fields = ['full_name', 'email']

class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('full_name', 'phone', 'email', 'password', 'is_active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class LoginForm(forms.Form):
    phone    = forms.CharField(label='Phone')
    password = forms.CharField(widget=forms.PasswordInput)
    
    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        request = self.request
        data = self.cleaned_data
        phone  = data.get("phone")
        password  = data.get("password")
        qs = User.objects.filter(phone=phone)
        if not qs.exists():
            raise forms.ValidationError("Mobile number not registered.")
        user = authenticate(request, username=phone, password=password)
        if user is None:
            raise forms.ValidationError("Invalid credentials")
        login(request, user)
        user_logged_in.send(user.__class__, instance=user, request=request)
        self.user = user
        return data

class SendOtpForm(forms.ModelForm):    
    class Meta:
        model = User
        fields = ('phone',)
        widgets = { 
            'phone': forms.TextInput(attrs={'id' : 'mobile-number'}),
        } 
    
    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        phone_regex = re.compile(r'^\d{10}$')
        if not phone_regex.match(phone):
            raise forms.ValidationError("Invalid phone number.")
        return phone
    
class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    otp = forms.CharField(label='OTP', widget=forms.TextInput)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('phone',)
        widgets = { 
            'phone': forms.TextInput(attrs={'readonly': '', 'id' : 'from-mobile-number'}),
        } 
        
    def clean_otp(self):
        phone = self.cleaned_data.get("otp")
        phone_regex = re.compile(r'^\d{4}$')
        if not phone_regex.match(phone):
            raise forms.ValidationError("Otp must be 4 digit number.")
        data = verify_otp(self.cleaned_data.get("phone"), self.cleaned_data.get("otp"))
        if "success" != data['type']:
            raise forms.ValidationError("OTP not verified." + data['message'])
        return self.cleaned_data.get("otp")
    
    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        phone_regex = re.compile(r'^\d{10}$')
        if not phone_regex.match(phone):
            raise forms.ValidationError("Invalid phone number.")
        return phone
    
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        validate_password(password1)
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match.")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

accounts/views.py
from .forms import LoginForm, RegisterForm, UserDetailChangeForm  
from django.views.generic import CreateView, FormView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from pustakalaywebsite.mixins import NextUrlMixin, RequestFormAttachMixin
from django.contrib.auth import authenticate, login
from .signals import user_logged_in
from django.shortcuts import render, redirect 
from django.urls import reverse
from django.contrib import messages
from accounts.forms import SendOtpForm
from sms.utils import send_otp

class AccountHomeView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/home.html'
    def get_object(self):
        return self.request.user

class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/login.html'
    default_next = '/'

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)

class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/account/details/'
    
    def get_initial(self):
        initial = super().get_initial()
        initial['phone'] = self.kwargs['phonenumber'] 
        return initial
    
    def form_valid(self, form):
        form.save()
        phone = self.request.POST['phone']
        password = self.request.POST['password1']
        user = authenticate(username=phone, password=password)
        login(self.request, user)
        user_logged_in.send(user.__class__, instance=user, request=self.request)
        return redirect(self.success_url)
    
class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'accounts/detail-update-view.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Your Account Details'
        return context

    def get_success_url(self):
        return reverse("account:home")
    
def send_otp_view(request):
    form = SendOtpForm(request.POST or None)
    if request.method == "POST" and form.is_valid():   
        phone_number = request.POST.get("phone") 
        data = send_otp(phone_number)
        if "success" == data['type']:
            request.session['otp-phone-number'] = phone_number    
            url = reverse('register_page', kwargs={'phonenumber':request.POST.get('phone')})  
            return redirect(url)
        else:
            messages.add_message(request, messages.ERROR, "Some Error occured while sending OTP.")
    return render(request, "accounts/send-otp.html", {'form' : form})

accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <label for='phone'>Phone</label>
  <input type='text' id='phone' class='form-control disabled' value='{{ request.user.phone }}' disabled="disabled" /><span class='help-text'>Cannot change phone</span><br/>
  <button type='submit' class='btn btn-light my-3'>Save</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
<div class='col-12'>
<h1>Account</h1>
<hr/>
</div>

<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Billing</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "orders:list" %}'>Orders</a>
                <a class='list-group-item' href='#'>Payment Methods</a>
                <a class='list-group-item' href='{% url "addresses:home" %}'>Addresses</a>
                
                
            </div>
      </div>
    </div>
</div>

<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Account Details</h4> 
            <div class='list-group'>
                <a class='list-group-item' href='{% url "account:user-update" %}'>Update Details</a>
                <a class='list-group-item' href='{% url "password_change" %}'>Change Password</a>
                
            </div>

      </div>
    </div>
</div>

<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Preferences</h4> 
            <div class='list-group'>
                <a class='list-group-item' href='#'>Email Marketing</a>
                
            </div>

      </div>
    </div>
</div>

<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">History</h4> 
              <div class='list-group'>
                <a class='list-group-item' href='{% url "account:user-book-history" %}'>Products Viewed</a>
            </div>
      </div>
    </div>
</div>

<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Support</h4>
            <div class='list-group'>
                <!-- <a class='list-group-item' href='#'>About</a> -->
                <a class='list-group-item' href='{% url "contact" %}'>Contact</a>
            </div>
      </div>
    </div>
</div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %} {% load static %} {% block content %}

{% if not request.user.is_authenticated%}
{% endif%}
<br>
<div class="container login_container">
	
<form method="POST">
	{% csrf_token %} {{ form }} 
	<input type="submit" value="Login">
</form>
<br>
<p>Not existing user?</p> 
<a href="{% url 'send-otp' %}">Register</a>
<br>
<p>Forgot Password?</p> 
<a href="{% url 'password_reset' %}">Reset Password</a>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %} {% load static %} {% block content %}
<br>
<div class="container">
<form method="POST">{% csrf_token %}
	{{ form }} 
	<button type='submit' class ='form-control col-md-1 btn btn-info'>Register</button>
</form>
</div>
<br>
<br>
<br>
<div>
<a href = '{% url "send-otp" %}'><button class = 'form-control col-md-1 btn btn-success'>Change Number</button></a>
</div>
<div>
<p class = 'resend-otp-text'>Haven't received OTP?</p>
<br>
<form class = 'resend-otp-form' action = '{% url "sms:resend-otp" %}' method = 'POST'> {% csrf_token %}
  <input class = 'form-control col-md-3' id = 'to-mobile-number-resend' type="hidden" name="phone-number" readonly maxlength="10" required>
  <button type='submit' class ='form-control col-md-1 btn btn-info'>Resend OTP</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/send-otp.html
{% extends "base.html" %} {% load static %} {% block content %}

<br>
<div class="container login_container">
<form method = 'POST'> {% csrf_token %}
  {{ form }}
  <button type='submit' class ='form-control col-md-1 btn btn-info'>Send OTP</button>
</form>
<button id = 'already-have-otp-button' class = 'form-control col-md-2 btn btn-primary' type="button" >Already have OTP</button>
{% endblock %}