pustakalaywebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from .views import home_page, contact_page, update_pincode
from accounts.views import LoginView, RegisterView
from django.contrib.auth import views as auth_views
from carts.views import cart_detail_api_view
from django.views.generic import RedirectView
from accounts.views import send_otp_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^update-pincode/$', update_pincode, name='update-pincode'),
    url(r'^sms/', include("sms.urls", namespace='sms')),
    url(r'^orders/', include("orders.urls", namespace='orders')),
    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/', include("addresses.urls", namespace='addresses')),
    url(r'^settings/$', RedirectView.as_view(url='/account')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include("accounts.urls", namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^register/(?P<phonenumber>\d+)/$', RegisterView.as_view(), name='register_page'),
    url(r'^sendotp/$', send_otp_view, name='send-otp'),
    url(r'^contact/$', contact_page, name='contact'),
    url('books/', include('booksapp.urls', namespace='books')),
    url('search/', include('search.urls', namespace='search')),
    url('cart/', include('carts.urls', namespace='carts')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/urls.py
from django.conf.urls import url
from .views import resend_otp, check_balance


urlpatterns = [
    url(r'^check-balance/$', check_balance, name='check-balance'),
    url(r'^resend-otp/$', resend_otp, name='resend-otp'),
    ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="description" content="">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>{% if title %} {{ title }} {% else %} Pustakalay {% endif %}</title>
<link rel="icon" type="image/ico" href="{% static 'img/title-icon.png' %}"/>
{% include 'css.html' %}
{% include 'js.html' %}
</head>
<body>
	{% include 'header.html' %}
      <div class='container'>
        {% if messages %}      
          {% for message in messages %}
          <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
              <div class="alert alert-danger messages">              
              {% else %}
              <div class="alert alert-success messages">
              {% endif %}
              {{ message }}<br/>
          </span>
          {% endfor %}
      </div>
      {% endif %}
	{% block content %} 
	{% endblock	%} 
	{% include 'footer.html' %}
</body>
</html>

templates/css.html
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href='{% static "/style.css" %}'>

templates/footer.html
{% load static %}
		<!-- FOOTER -->

<!--	<footer class="footer-classic">
		<div class="container">
			<div class="row row-30">
				<div class="col-md-4 col-xl-5">
					<div class="pr-xl-4">
						<a class="brand" href="index.html"><img
							class="brand-logo-light"
							src="images/agency/logo-inverse-140x37.png" alt="" width="140"
							height="37"
							srcset="images/agency/logo-retina-inverse-280x74.png 2x"></a>
						<p>We are an award-winning creative agency, dedicated to the
							best result in web design, promotion, business consulting, and
							marketing.</p>
						<!-- Rights-->
<!--						<p class="rights">
							<span class="copyright-year">2019</span> <span>Pustakalay</span> <span>All
								Rights Reserved.</span>
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<h5>Contacts</h5>
					<dl class="contact-list">
						<dt>Address:</dt>
						<dd>798 South Park Avenue, Jaipur, Raj</dd>
					</dl>
					<dl class="contact-list">
						<dt>email:</dt>
						<dd>
							<a href="mailto:#">dkstudioin@gmail.com</a>
						</dd>
					</dl>
					<dl class="contact-list">
						<dt>phones:</dt>
						<dd>
							<a href="tel:#">+91 7568543012</a> <span>or</span> <a
								href="tel:#">+91 9571195353</a>
						</dd>
					</dl>
				</div>
				<div class="col-md-4 col-xl-3">
					<h5>Links</h5>
					<ul class="nav-list">
						<li><a href="#">About</a></li>
						<li><a href="#">Projects</a></li>
						<li><a href="#">Blog</a></li>
						<li><a href="#">Contacts</a></li>
						<li><a href="#">Pricing</a></li>
					</ul>
				</div> -->
			</div>
		</div>
		<!-- <div class="row no-gutters social-container">
			<div class="col">
				<a class="social-inner" href="#"><span
					class="icon mdi mdi-facebook"></span><span>Facebook</span></a>
			</div>
			<div class="col">
				<a class="social-inner" href="#"><span
					class="icon mdi mdi-instagram"></span><span>instagram</span></a>
			</div>
			<div class="col">
				<a class="social-inner" href="#"><span
					class="icon mdi mdi-twitter"></span><span>twitter</span></a>
			</div>
			<div class="col">
				<a class="social-inner" href="#"><span
					class="icon mdi mdi-youtube-play"></span><span>google</span></a>
			</div>
		</div> -->
	</footer>

templates/header.html
{% load static %}
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'books:bookslist' as book_list_url %}
{% url 'login' as login_url %}
{% url 'register_page' as register_url %}
{% url 'logout' as logout_url %}
{% url 'carts:home' as cart_url %}
{% url 'account:home' as account_url %}

	<!--  Header -->
	<header class="header_area mb-3" >
		<div
			class="classy-nav-container breakpoint-off d-flex align-items-center justify-content-between">

			<nav class="classy-navbar" id="class_nav">
				<!-- Logo -->
				<a class="nav-brand" href="{{ home_url }}">
					<!-- <img src="{% static 'img/title-icon.png' %}"> -->
					<h3>PUSTAKALAY</h3>
				</a>
				<!-- Navbar Toggler -->
				<div class="classy-navbar-toggler">
					<span class="navbarToggler"><span></span><span></span><span></span></span>
				</div>
				<!-- Menu -->
				<div class="classy-menu">
					<!-- close btn -->
					<div class="classycloseIcon">
						<div class="cross-wrap">
							<span class="top"></span><span class="bottom"></span>
						</div>
					</div>
					<!-- Nav Start -->
					<div class="classynav">
						<ul>
							<li><a class="{% if request.path == login_url %}active{% endif %}" href="{{book_list_url}}">Books</a>
								<!-- <div class="megamenu">
									<ul class="single-mega cn-col-4">
										<li class="title">Category1</li>
										<li><a href="#">subcategory</a></li>
										<li><a href="#">subcategory</a></li>
										<li><a href="#">subcategory</a></li>
										<li><a href="#">subcategory</a></li>
										<li><a href="#">subcategory</a></li>
									</ul>
									<ul class="single-mega cn-col-4">
										<li class="title">Category1</li>
										<li><a href="#">subcategory</a></li>
										<li><a href="#">subcategory</a></li>
										<li><a href="#">subcategory</a></li>
										<li><a href="#">subcategory</a></li>
										<li><a href="#">subcategory</a></li>
									</ul>
									<ul class="single-mega cn-col-4">
										<li class="title">Category1</li>
										<li><a href="#">subcategory</a></li>
										<li><a href="#">subcategory</a></li>
										<li><a href="#">subcategory</a></li>
										<li><a href="#">subcategory</a></li>
										<li><a href="#">subcategory</a></li>
									</ul>
								</div></li> -->
							<!-- <li><a href="#">Pages</a>
								<ul class="dropdown">
									<li><a href="#">Page2</a></li>

								</ul></li> -->
							<li><a class="{% if request.path == login_url %}active{% endif %}" href="{{contact_url}}">Contact</a></li>
						</ul>
					</div>
					<!-- Nav End -->
				</div>
			</nav>

			<!-- Header Meta Data -->
			<div class="header-meta d-flex clearfix justify-content-end">
				{% include 'pincode/pincode-form.html' with pincode_form=pincode_form pincode=pincode next_url=request.build_absolute_uri is_deliverable=True%}
				{% include 'search/snippets/search_form.html' %}
				<!-- User-->
				<div class="user-login-info {% if request.path == login_url %}active{% endif %}">
					{% if user.is_authenticated %}
					<!-- <p>
						<a class="logged_in" >Hi {{ user.username }}</a>
						<span><a class="logged_in" href="{{logout_url}}">Logout <i class="fa fa-power-off" aria-hidden="true"></i></a></span>
						
					</p> -->
					<li class="nav-item dropdown"><a class="nav-link dropdown-toggle"
						href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
						aria-haspopup="true" aria-expanded="false"> Account </a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item {% if request.path == account_url %}active{% endif %}"								
								href="{{ account_url }}">Home</a> 
					          <a class="dropdown-item" href='{% url "orders:list" %}'>Orders</a>
					          <a class="dropdown-item" href='{% url "addresses:home" %}'>Addresses</a>
					          <a class="dropdown-item" href='{% url "account:user-book-history" %}'>Products Viewed</a>
					          <a class="dropdown-item" href='{% url "password_change" %}'>Change Password</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{{ logout_url }}">Logout</a>
						</div>
					</li>
					{% else %} <a class="log_in" href="{{login_url}}"><img
						src='{% static "img/core-img/user.svg" %}' alt="Login"></a> 
						{% endif %}
				</div>
				<!-- Cart -->
				<div class="cart-area">
					<a href="{{cart_url}}"><span class='cart-area navbar-cart-count'>{{ request.session.cart_item_count }}</span><img src='{% static "img/core-img/bag.svg" %}'
						alt=""> <span></span></a>
				</div>
			</div>

		</div>
	</header>

templates/home_page.html
{% extends "base.html" %} {% load static %} {% block content %}

<!-- Main content -->
<div class="container">
	<div id="carouselExampleIndicators" class="carousel slide home_slider"
		data-ride="carousel">
		<ol class="carousel-indicators">
			<li data-target="#carouselExampleIndicators" data-slide-to="0"
				class="active"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner">
			<div class="carousel-item active">
				<img class="d-block w-100 slides"
					src='{% static "img/slider1.jpg" %}' alt="First slide">
			</div>
			<div class="carousel-item">
				<img class="d-block w-100 slides"
					src='{% static "img/slider2.jpg" %}' alt="Second slide">
			</div>
			<div class="carousel-item">
				<img class="d-block w-100 slides"
					src='{% static "img/slider3.jpg" %}' alt="Third slide">
			</div>
		</div>
		<a class="carousel-control-prev" href="#carouselExampleIndicators"
			role="button" data-slide="prev"> <span
			class="carousel-control-prev-icon" aria-hidden="true"></span> <span
			class="sr-only">Previous</span>
		</a> <a class="carousel-control-next" href="#carouselExampleIndicators"
			role="button" data-slide="next"> <span
			class="carousel-control-next-icon" aria-hidden="true"></span> <span
			class="sr-only">Next</span>
		</a>
	</div>
</div>

<div class="container text-center" id="stock_container">
	<h1 class="global_header">NEW ARRIVALS</h1>
	<div class="row">
		<div class="col-lg-2 book_container">
			<!-- Books added goes here -->
		</div>
		<div class="col-lg-2 book_container"></div>
		<div class="col-lg-2 book_container"></div>
		<div class="col-lg-2 book_container"></div>
		<div class="col-lg-2 book_container"></div>
		<div class="col-lg-2 book_container"></div>
	</div>
</div>
<div class="container text-center" id="stock_container">
	<h1 class="global_header">BEST SELLERS</h1>
	<div class="row">
		<div class="col-sm-4 col-lg-2 book_container"></div>
		<div class="col-sm-4 col-lg-2 book_container"></div>
		<div class="col-sm-4 col-lg-2 book_container"></div>
		<div class="col-sm-4 col-lg-2 book_container"></div>
		<div class="col-sm-4 col-lg-2 book_container"></div>
		<div class="col-sm-4 col-lg-2 book_container"></div>
	</div>
</div>
<div class="container text-center" id="stock_container">
	<h1 class="global_header">AWARD WINNER</h1>
	<div class="row">
		<div class="col-lg-2 book_container"></div>
		<div class="col-lg-2 book_container"></div>
		<div class="col-lg-2 book_container"></div>
		<div class="col-lg-2 book_container"></div>
		<div class="col-lg-2 book_container"></div>
		<div class="col-lg-2 book_container"></div>
	</div>
</div>
<div class="container text-center" id="stock_container">
	<h1 class="global_header">FEATURED AUTHOR</h1>
	<div class="row">
		<div class="col-lg-2 author_container"></div>
		<div class="col-lg-2 author_container"></div>
		<div class="col-lg-2 author_container"></div>
		<div class="col-lg-2 author_container"></div>
		<div class="col-lg-2 author_container"></div>
		<div class="col-lg-2 author_container"></div>
	</div>
</div>

{% endblock %}

templates/js.html
{% load static %}
<script src='{% static "js/jquery/jquery-2.2.4.min.js" %}'></script>
<!-- Popper js -->
<script src='{% static "js/popper.min.js" %}'></script>
<!-- Bootstrap js -->
<script src='{% static "js/bootstrap.min.js" %}'></script>
<!-- Classy Nav js -->
<script src='{% static "js/classy-nav.min.js" %}'></script>
<!-- Active js -->
<script src='{% static "js/active.js" %}'></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<script	src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src='{% static "js/my-ajax.js" %}'></script>
<!-- Django Secure AJAX JS -->
<script src='{% static "js/csrf.ajax.js" %}'></script>

<!-- jquery-confirm JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>